### ISSUE TITLE
Les densités ne sont pas précises

### ISSUE THREAD

**Issue by codeSamuraii** [codeSamuraii/Lifie#1]
La densité globale et les densités spécifiques ne semblent pas être appropriées.

**Comment by Yves-Olsen** [comment]
Pourquoi?

**Comment by codeSamuraii** [comment]
Elles montent à plus de 100%.

**Comment by Yves-Olsen** [comment]
En fait, le programme fonctionne lorsqu'on met une densité supérieure à 1 uniquement si une (ou plus) des densités précédentes est inférieure à 1. Par exemple :    
densites = {
    "sable"     : (densite_cible / 100),
    "plaine"    :  1.8,
    "foret"     : 0.5,
    "montagne"  : 0.50,
    "neige"     : 0.20 }
fonctionne (avec densite_cible = 50 par exemple).

Je donne un exemple pour illustrer pourquoi:

considère "plaine" : 0.2. et "foret" : 1.8 Le programme pose des disques ou des rectangles de foret dont **le centre** est sur de la plaine, mais le reste du disque peut être ailleurs que sur de la plaine, du coup, il peut y avoir plus de pixels de foret que de pixels de plaine donc (ile == entiers[terrain]).sum() / densite_precedente peut être supérieur à 1. Pour remédier au problème, on peut augmenter taillemax_terrain.
